/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora.java.layout;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author Vanilson
 */
public class Sobre extends javax.swing.JFrame {

    /**
     * Creates new form Sobre
     */
    public Sobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLink = new javax.swing.JButton();
        btLink2 = new javax.swing.JButton();
        lDescricao = new javax.swing.JLabel();
        lDescricao2 = new javax.swing.JLabel();
        linkdIn = new javax.swing.JLabel();
        lFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora em Java");
        setResizable(false);

        btLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/java/imgs/logo-github.png"))); // NOI18N
        btLink.setBorder(null);
        btLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLinkActionPerformed(evt);
            }
        });

        btLink2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/java/imgs/logo-linkedin.png"))); // NOI18N
        btLink2.setBorder(null);
        btLink2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLink2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLink2ActionPerformed(evt);
            }
        });

        lDescricao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDescricao.setText("Desenvolvido por Luiz. F. R. Pimentel");

        lDescricao2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lDescricao2.setText("<html>\nEsta calculadora, foi criada utilizando o NetBeans para programar em Java.\n<br/>\n<html/>");

        linkdIn.setText("<html> Conheça mais Sobre -->   <html/>");

        lFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/java/layout/fundo-sobre.png"))); // NOI18N
        lFundo.setPreferredSize(new java.awt.Dimension(350, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(btLink))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(linkdIn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(btLink2))
            .addComponent(lFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btLink))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(linkdIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btLink2))
            .addComponent(lFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        linkdIn.getAccessibleContext().setAccessibleName("linkdIn");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLinkActionPerformed
        gitHub();
    }//GEN-LAST:event_btLinkActionPerformed

    private void btLink2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLink2ActionPerformed
        linkdIn();
    }//GEN-LAST:event_btLink2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobre().setVisible(true);
            }
        });
    }

// Abre pagina do linkdIn no navegador
    
    private void linkdIn(){
        try {
            URI link = new URI("https://www.linkedin.com/in/luiz-fernando-rocha-pimentel-b04a18154/");
            
            Desktop.getDesktop().browse(link);
            } catch(IOException | URISyntaxException erro){
            System.out.println(erro);
        }
    }
    
// Abre a pagina do GitHub no navegador
    
    private void gitHub(){
        try {
            URI link = new URI("https://github.com/KanekiZLF");
            
            Desktop.getDesktop().browse(link);
            } catch(IOException | URISyntaxException erro){
            System.out.println(erro);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLink;
    private javax.swing.JButton btLink2;
    private javax.swing.JLabel lDescricao;
    private javax.swing.JLabel lDescricao2;
    private javax.swing.JLabel lFundo;
    private javax.swing.JLabel linkdIn;
    // End of variables declaration//GEN-END:variables
}
